Hooks.once('sequencer.ready', () => {
        const PATH = "modules/animated-spell-effects-cartoon/spell-effects/cartoon";
        const cartoonDatabase = {
            "air": {
                "blast": {
                    "circle": `${PATH}/air/air_blast_CIRCLE_01.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_01.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_02.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_03.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_04.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_05.webm`,
                },
                "bolt": {
                    "ray": `${PATH}/air/air_bolt_RAY_01.webm`,
                    "square": `${PATH}/air/air_bolt_SQUARE_01.webm`,
                    "square": `${PATH}/air/air_bolt_SQUARE_02.webm`,
                },
                "explosion": {
                    "gray": `${PATH}/air/air_explosion_800x800.webm`,
                    "blue": `${PATH}/air/air_explosion_blue_800x800.webm`,
                    "green": `${PATH}/air/air_explosion_green_800x800.webm`,
                    "purple": `${PATH}/air/air_explosion_purple_800x800.webm`,
                    "red": `${PATH}/air/air_explosion_red_800x800.webm`,
                    "yellow": `${PATH}/air/air_explosion_yellow_800x800.webm`,
                },
                "gust": {
                    "gray": `${PATH}/air/air_gust_800x800.webm`,
                    "blue": `${PATH}/air/air_gust_blue_800x800.webm`,
                    "green": `${PATH}/air/air_gust_green_800x800.webm`,
                    "purple": `${PATH}/air/air_gust_purple_800x800.webm`,
                    "red": `${PATH}/air/air_gust_red_800x800.webm`,
                    "square": `${PATH}/air/air_gust_SQUARE_01.webm`,
                    "yellow": `${PATH}/air/air_gust_yellow_800x800.webm`,
                },
                "infinity": `${PATH}/air/air_infinity_RECTANGLE_01.webm`,
                "portal": `${PATH}/air/air_portal_CIRCLE_01.webm`,
                "puff": {
                    "01": `${PATH}/air/air_puff_CIRCLE_01.webm`,
                    "02": `${PATH}/air/air_puff_CIRCLE_02.webm`,
                    "03": `${PATH}/air/air_puff_CIRCLE_03.webm`,
                },
                "spiral": {
                    "gray": `${PATH}/air/air_spiral_800x800.webm`,
                    "blue": `${PATH}/air/air_spiral_blue_800x800.webm`,
                    "green": `${PATH}/air/air_spiral_green_800x800.webm`,
                    "purple": `${PATH}/air/air_spiral_purple_800x800.webm`,
                    "red": `${PATH}/air/air_spiral_red_800x800.webm`,
                    "yellow": `${PATH}/air/air_spiral_yellow_800x800.webm`,
                },
                "wall": `${PATH}/air/air_wall_SQUARE_01.webm`,
            },
            "cantrips": {
                "acid_splash": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/acid_splash_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/acid_splash_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/acid_splash_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/acid_splash_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/acid_splash_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_yellow_90ft.webm`,
                    },
                },
                "eldritch_blast": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_yellow_90ft.webm`,
                    },
                },
                "fire_bolt": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/fire_bolt_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/fire_bolt_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/fire_bolt_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/fire_bolt_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/fire_bolt_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_yellow_90ft.webm`,
                    },
                },
                "frostbite": `${PATH}/cantrips/gust_800x800.webm`, 
                "gust": {
                    "15ft": `${PATH}/cantrips/gust_15ft.webm`, 
                    "800x800": `${PATH}/cantrips/gust_800x800.webm`,
                },
                "lightning_lure": {
                    "blue": `${PATH}/cantrips/lightning_lure_blue_15ft.webm`,
                    "green": `${PATH}/cantrips/lightning_lure_green_15ft.webm`,
                    "purple": `${PATH}/cantrips/lightning_lure_purple_15ft.webm`,
                    "red": `${PATH}/cantrips/lightning_lure_red_15ft.webm`,
                    "yellow": `${PATH}/cantrips/lightning_lure_yellow_15ft.webm`,
                },
                "mending": {
                    "blue": `${PATH}/cantrips/mending_blue_800x800.webm`,
                    "green": `${PATH}/cantrips/mending_green_800x800.webm`,
                    "purple": `${PATH}/cantrips/mending_purple_800x800.webm`,
                    "red": `${PATH}/cantrips/mending_red_800x800.webm`,
                    "yellow": `${PATH}/cantrips/mending_yellow_800x800.webm`,
                },
                "poison_spray": {
                    "blue": `${PATH}/cantrips/poison_spray_blue_10ft.webm`,
                    "green": `${PATH}/cantrips/poison_spray_green_10ft.webm`,
                    "purple": `${PATH}/cantrips/poison_spray_purple_10ft.webm`,
                    "red": `${PATH}/cantrips/poison_spray_red_10ft.webm`,
                    "yellow": `${PATH}/cantrips/poison_spray_yellow_10ft.webm`,
                },
                "ray_of_frost": {
                    "05ft": `${PATH}/cantrips/ray_of_frost_5ft.webm`,
                    "15ft": `${PATH}/cantrips/ray_of_frost_15ft.webm`,
                    "30ft": `${PATH}/cantrips/ray_of_frost_30ft.webm`,
                    "60ft": `${PATH}/cantrips/ray_of_frost_60ft.webm`,
                },
                "sacred_flame": {
                    "blue": `${PATH}/cantrips/sacred_flame_blue_800x800.webm`,
                    "green": `${PATH}/cantrips/sacred_flame_green_800x800.webm`,
                    "purple": `${PATH}/cantrips/sacred_flame_purple_800x800.webm`,
                    "red": `${PATH}/cantrips/sacred_flame_red_800x800.webm`,
                    "yellow": `${PATH}/cantrips/sacred_flame_yellow_800x800.webm`,
                },
                "shocking_grasp": {
                    "blue": `${PATH}/cantrips/shocking_grasp_blue_5ft.webm`,
                    "green": `${PATH}/cantrips/shocking_grasp_green_5ft.webm`,
                    "purple": `${PATH}/cantrips/shocking_grasp_purple_5ft.webm`,
                    "red": `${PATH}/cantrips/shocking_grasp_red_5ft.webm`,
                    "yellow": `${PATH}/cantrips/shocking_grasp_yellow_5ft.webm`,
                },
            },
            "conditions": {
                "blinded": `${PATH}/conditions/condition_blinded_800x800.webm`,
                "charmed": `${PATH}/conditions/condition_charmed_800x800.webm`,
                "deafened": `${PATH}/conditions/condition_deafened_800x800.webm`,
                "exhaustion": `${PATH}/conditions/condition_exhaustion_800x800.webm`,
                "frightened": `${PATH}/conditions/condition_frightened_800x800.webm`,
                "grappled": `${PATH}/conditions/condition_grappled_800x800.webm`,
                "incapacitated": `${PATH}/conditions/condition_incapacitated_800x800.webm`,
                "invisible": `${PATH}/conditions/condition_invisible_800x800.webm`,
                "paralyzed": `${PATH}/conditions/condition_paralyzed_800x800.webm`,
                "petrified": `${PATH}/conditions/condition_petrified_800x800.webm`,
                "poisoned": `${PATH}/conditions/condition_poisoned_800x800.webm`,
                "prone": `${PATH}/conditions/condition_prone_800x800.webm`,
                "restrained": `${PATH}/conditions/condition_restrained_800x800.webm`,
                "stunned": `${PATH}/conditions/condition_stunned_800x800.webm`,
                "unconcious": `${PATH}/conditions/condition_unconcious_800x800.webm`,
            },
            "earth": {
                "debris": {
                    "01": `${PATH}/earth/debris_01_800x800.webm`,
                    "02": `${PATH}/earth/debris_02_800x800.webm`,
                    "03": `${PATH}/earth/debris_03_800x800.webm`,
                    "04": `${PATH}/earth/debris_04_800x800.webm`,
                    "05": `${PATH}/earth/debris_05_800x800.webm`,
                },
                "crack": `${PATH}/earth/earth_crack_SQUARE_01.webm`,
                "explosion": {
                    "01": `${PATH}/earth/earth_explosion_SQUARE_01.webm`,
                    "02": `${PATH}/earth/earth_explosion_SQUARE_02.webm`,
                    "03": `${PATH}/earth/earth_explosion_SQUARE_03.webm`,
                },
                "slam": `${PATH}/earth/earth_slam_RECTANGLE_01.webm`,
                "spike": `${PATH}/earth/earth_spike_CIRCLE_01.webm`,
                "plant": {
                    "growing01": `${PATH}/earth/plant_growing_SQUARE_01.webm`,
                    "growing02": `${PATH}/earth/plant_growing_SQUARE_01.webm`,
                },
            },
            "electricity": {
                "01": `${PATH}/electricity/electricity_01_800x800.webm`,
                "02": `${PATH}/electricity/electricity_02_800x800.webm`,
                "03": `${PATH}/electricity/electricity_03_800x800.webm`,
                "04": `${PATH}/electricity/electricity_04_800x800.webm`,
                "05": `${PATH}/electricity/electricity_05_800x800.webm`,
                "06": `${PATH}/electricity/electricity_06_800x800.webm`,
                "07": `${PATH}/electricity/electricity_07_800x800.webm`,
                "08": `${PATH}/electricity/electricity_08_800x800.webm`,
                "09": `${PATH}/electricity/electricity_09_800x800.webm`,
                "10": `${PATH}/electricity/electricity_10_800x800.webm`,
                "15": `${PATH}/electricity/electricity_15_800x800.webm`,
                "16": `${PATH}/electricity/electricity_16_800x800.webm`,
                "17": `${PATH}/electricity/electricity_17_800x800.webm`,
                "18": `${PATH}/electricity/electricity_18_800x800.webm`,
                "19": `${PATH}/electricity/electricity_19_800x800.webm`,
                "20": `${PATH}/electricity/electricity_20_800x800.webm`,
                "21": `${PATH}/electricity/electricity_21_800x800.webm`,
                "22": `${PATH}/electricity/electricity_22_800x800.webm`,
                "23": `${PATH}/electricity/electricity_23_800x800.webm`,
                "24": `${PATH}/electricity/electricity_24_800x800.webm`,
                "25": `${PATH}/electricity/electricity_25_800x800.webm`,
                "26": `${PATH}/electricity/electricity_26_800x800.webm`,
                "27": `${PATH}/electricity/electricity_27_800x800.webm`,
                "28": `${PATH}/electricity/electricity_28_800x800.webm`,
                "29": `${PATH}/electricity/electricity_29_800x800.webm`,
                "30": `${PATH}/electricity/electricity_30_800x800.webm`,
                "31": `${PATH}/electricity/electricity_31_800x800.webm`,
                "32": `${PATH}/electricity/electricity_32_800x800.webm`,
                "33": `${PATH}/electricity/electricity_33_800x800.webm`,
                "34": `${PATH}/electricity/electricity_34_800x800.webm`,
                "35": `${PATH}/electricity/electricity_35_800x800.webm`,
                "36": `${PATH}/electricity/electricity_36_800x800.webm`,
                "37": `${PATH}/electricity/electricity_37_800x800.webm`,
                "blast": {
                  "01": `${PATH}/electricity/electricity_blast_CIRCLE.webm`,
                  "02": `${PATH}/electricity/electric_blast_01.webm`,
                  "03": `${PATH}/electricity/electric_blast_RECTANGLE_02.webm`,
                  "04": `${PATH}/electricity/electrivity_blast_CIRCLE.webm`,
                },
                "pulse": `${PATH}/electricity/electricity_pulse_CIRCLE_01.webm`,
                "ball": {
                    "01": `${PATH}/electricity/electric_ball_CIRCLE_01.webm`,
                    "03": `${PATH}/electricity/electric_ball_CIRCLE_03.webm`,
                    "04": `${PATH}/electricity/electric_ball_CIRCLE_04.webm`,
                    "05": `${PATH}/electricity/electric_ball_CIRCLE_05.webm`,
                    "06": `${PATH}/electricity/electric_ball_CIRCLE_06.webm`,
                    "07": `${PATH}/electricity/electric_ball_CIRCLE_07.webm`,
                    "08": `${PATH}/electricity/electric_ball_CIRCLE_08.webm`,
                },
                "discharge": {
                    "01": `${PATH}/electricity/electric_discharge_CIRCLE_07.webm`,
                    "02": `${PATH}/electricity/electric_discharge_RECTANGLE_02.webm`,
                    "03": `${PATH}/electricity/electric_discharge_RECTANGLE_04.webm`,
                    "04": `${PATH}/electricity/electric_discharge_RECTANGLE_05.webm`,
                    "05": `${PATH}/electricity/electric_discharge_SQUARE_06.webm`,
                    "06": `${PATH}/electricity/electric_disharge_CIRCLE_01.webm`,
                    "07": `${PATH}/electricity/electric_disharge_CIRCLE_03.webm`,
                    "08": `${PATH}/electricity/electric_dishcarge_CIRCLE_09.webm`,
                    "09": `${PATH}/electricity/electric_dishcarge_SQUARE_08.webm`,
                    "10": `${PATH}/electricity/electric_dishcarge_SQUARE_09.webm`,
                },
                "fire_explosion": {
                    "01": `${PATH}/electricity/electric_fire_explosion_CIRCLE_01.webm`,
                    "02": `${PATH}/electricity/electric_fire_explosion_CIRCLE_02.webm`,
                },
                "shockwave": {
                    "blue": `${PATH}/electricity/electric_shockwave_blue_CIRCLE.webm`,
                    "green": `${PATH}/electricity/electric_shockwave_green_CIRCLE.webm`,
                    "purple": `${PATH}/electricity/electric_shockwave_purple_CIRCLE.webm`,
                    "red": `${PATH}/electricity/electric_shockwave_red_CIRCLE.webm`,
                    "yellow": `${PATH}/electricity/electric_shockwave_yellow_CIRCLE.webm`,
                },
                "wave": `${PATH}/electricity/electric_wave_SQUARE_01.webm`,
                "wheel": `${PATH}/electricity/electric_wheel_loop_RECTANGLE.webm`,
                "wifi": {
                    "01": `${PATH}/electricity/electric_wifi_SQUARE_01.webm`,
                    "02": `${PATH}/electricity/electric_wifi_SQUARE_02.webm`,
                },
                "triangle": `${PATH}/electricity/electrivity_triangle_CONE_01.webm`,
                "ray": {
                    "01": `${PATH}/electricity/lightning_blast_01_r2l.webm`,
                    "02": `${PATH}/electricity/lightning_blast_RAY_02.webm`,
                    "03": `${PATH}/electricity/lightning_blast_RECTANGLE_01.webm`,
                },
                "bolt": {
                    "01": `${PATH}/electricity/lightning_bolt_RECTANGLE_01.webm`,
                    "02": `${PATH}/electricity/lightning_bolt_RECTANGLE_02.webm`,
                    "03": `${PATH}/electricity/lightning_bolt_RECTANGLE_03.webm`,
                    "04": `${PATH}/electricity/lightning_bolt_RECTANGLE_04.webm`,
                    "05": `${PATH}/electricity/lightning_bolt_RECTANGLE_05.webm`,
                    "06": `${PATH}/electricity/lightning_bolt_RECTANGLE_06.webm`,
                    "07": `${PATH}/electricity/lightning_bolt_RECTANGLE_07.webm`,
                },
                "cone": `${PATH}/electricity/lightning_breath_CONE_01.webm`,
                "curves": `${PATH}/electricity/lightning_chaotic_curves_RECTANGLE_01.webm`,
                "ring": `${PATH}/electricity/ring_CIRCLE_01.webm`,
            },
            "energy": {
                "01": `${PATH}/energy/energy_01_800x800.webm`,
                "02": `${PATH}/energy/energy_02_800x800.webm`,
                "03": `${PATH}/energy/energy_03_800x800.webm`,
                "04": `${PATH}/energy/energy_04_800x800.webm`,
                "05": `${PATH}/energy/energy_05_800x800.webm`,
                "06": `${PATH}/energy/energy_06_800x800.webm`,
                "07": `${PATH}/energy/energy_07_800x800.webm`,
                "08": `${PATH}/energy/energy_08_800x800.webm`,
                "09": `${PATH}/energy/energy_09_800x800.webm`,
                "10": `${PATH}/energy/energy_10_800x800.webm`,
                "11": `${PATH}/energy/energy_11_800x800.webm`,
                "12": `${PATH}/energy/energy_12_800x800.webm`,
                "13": `${PATH}/energy/energy_13_800x800.webm`,
                "14": `${PATH}/energy/energy_14_800x800.webm`,
                "15": `${PATH}/energy/energy_15_800x800.webm`,
                "16": `${PATH}/energy/energy_16_800x800.webm`,
                "17": `${PATH}/energy/energy_17_800x800.webm`,
                "18": `${PATH}/energy/energy_18_800x800.webm`,
                "19": `${PATH}/energy/energy_19_800x800.webm`,
                "20": `${PATH}/energy/energy_20_800x800.webm`,
                "21": `${PATH}/energy/energy_21_800x800.webm`,
                "22": `${PATH}/energy/energy_22_800x800.webm`,
                "23": `${PATH}/energy/energy_23_800x800.webm`,
                "24": `${PATH}/energy/energy_24_800x800.webm`,
                "25": `${PATH}/energy/energy_25_800x800.webm`,
                "26": `${PATH}/energy/energy_26_800x800.webm`,
                "27": `${PATH}/energy/energy_27_800x800.webm`,
                "28": `${PATH}/energy/energy_28_800x800.webm`,
                "29": `${PATH}/energy/energy_29_800x800.webm`,
                "30": `${PATH}/energy/energy_30_800x800.webm`,
                "31": `${PATH}/energy/energy_31_800x800.webm`,
                "32": `${PATH}/energy/energy_32_800x800.webm`,
                "33": `${PATH}/energy/energy_33_800x800.webm`,
                "34": `${PATH}/energy/energy_34_800x800.webm`,
                "35": `${PATH}/energy/energy_35_800x800.webm`,
                "ball": `${PATH}/energy/energy_ball_CIRCLE.webm`,
                "beam": {
                    "01": `${PATH}/energy/energy_beam_RECTANGLE_01_l2r.webm`,
                    "02": `${PATH}/energy/energy_beam_RAY_02.webm`,
                },
                "blast": {
                    "01": `${PATH}/energy/energy_blasts_RECTANGLE_01.webm`,
                    "02": `${PATH}/energy/energy_blasts_SQUARE_01.webm`,
                    "03": `${PATH}/energy/energy_blast_CONE_05.webm`,
                    "04": `${PATH}/energy/energy_blast_RAY_01.webm`,
                    "05": `${PATH}/energy/energy_blast_RAY_03.webm`,
                    "06": `${PATH}/energy/energy_blast_RAY_04.webm`,
                    "07": `${PATH}/energy/energy_blast_RAY_05.webm`,
                },
                "explosion": `${PATH}/energy/energy_explosion_SQUARE_01.webm`,
                "flash": `${PATH}/energy/energy_flash_CIRCLE.webm`,
                "pulse": {
                    "blue": `${PATH}/energy/energy_pulse_blue_CIRCLE.webm`,
                    "green": `${PATH}/energy/energy_pulse_green_CIRCLE.webm`,
                    "purple": `${PATH}/energy/energy_pulse_purple_CIRCLE.webm`,
                    "red": `${PATH}/energy/energy_pulse_red_CIRCLE.webm`,
                    "yellow": `${PATH}/energy/energy_pulse_yellow_CIRCLE.webm`,
                },
                "quickburst": `${PATH}/energy/energy_quickburst_SQUARE_02.webm`,
                "spark": {
                    "01": `${PATH}/energy/energy_spark_CIRCLE_01.webm`,
                    "02": `${PATH}/energy/energy_spark_CIRCLE_02.webm`,
                },
                "tentacles": `${PATH}/energy/energy_tentacles_SQUARE.webm`,
                "wheel": `${PATH}/energy/energy_wheel_loop_CIRCLE.webm`,
            },
            "explosions": {
                "01": `${PATH}/explosions/explosions_01_800x800.webm`,
                "02": `${PATH}/explosions/explosions_02_800x800.webm`,
                "03": `${PATH}/explosions/explosions_03_800x800.webm`,
                "04": `${PATH}/explosions/explosions_04_800x800.webm`,
                "05": `${PATH}/explosions/explosions_05_800x800.webm`,
                "06": `${PATH}/explosions/explosions_06_800x800.webm`,
                "07": `${PATH}/explosions/explosions_07_800x800.webm`,
                "08": `${PATH}/explosions/explosions_08_800x800.webm`,
                "09": `${PATH}/explosions/explosions_09_800x800.webm`,
                "10": `${PATH}/explosions/explosions_10_800x800.webm`,
                "11": `${PATH}/explosions/explosions_11_800x800.webm`,
                "12": `${PATH}/explosions/explosions_12_800x800.webm`,
                "13": `${PATH}/explosions/explosions_13_800x800.webm`,
                "14": `${PATH}/explosions/explosions_14_800x800.webm`,
                "15": `${PATH}/explosions/explosions_15_800x800.webm`,
                "16": `${PATH}/explosions/explosions_16_800x800.webm`,
                "17": `${PATH}/explosions/explosions_17_800x800.webm`,
                "18": `${PATH}/explosions/explosions_18_800x800.webm`,
            },
            "fire": {
                "01": `${PATH}/fire/fire_01_800x800.webm`,
                "02": `${PATH}/fire/fire_02_800x800.webm`,
                "03": `${PATH}/fire/fire_03_800x800.webm`,
                "04": `${PATH}/fire/fire_04_800x800.webm`,
                "05": `${PATH}/fire/fire_05_800x800.webm`,
                "06": `${PATH}/fire/fire_06_800x800.webm`,
                "07": `${PATH}/fire/fire_07_800x800.webm`,
                "08": `${PATH}/fire/fire_08_800x800.webm`,
                "09": `${PATH}/fire/fire_09_800x800.webm`,
                "10": `${PATH}/fire/fire_10_800x800.webm`,
                "11": `${PATH}/fire/fire_11_800x800.webm`,
                "12": `${PATH}/fire/fire_12_800x800.webm`,
                "13": `${PATH}/fire/fire_13_800x800.webm`,
                "14": `${PATH}/fire/fire_14_800x800.webm`,
                "15": `${PATH}/fire/fire_15_800x800.webm`,
                "16": `${PATH}/fire/fire_16_800x800.webm`,
                "17": `${PATH}/fire/fire_17_800x800.webm`,
                "18": `${PATH}/fire/fire_18_800x800.webm`,
                "19": `${PATH}/fire/fire_19_800x800.webm`,
                "20": `${PATH}/fire/fire_20_800x800.webm`,
                "21": `${PATH}/fire/fire_21_800x800.webm`,
                "22": `${PATH}/fire/fire_22_800x800.webm`,
                "23": `${PATH}/fire/fire_23_800x800.webm`,
                "24": `${PATH}/fire/fire_24_800x800.webm`,
                "25": `${PATH}/fire/fire_25_800x800.webm`,
                "26": `${PATH}/fire/fire_26_800x800.webm`,
                "27": `${PATH}/fire/fire_27_800x800.webm`,
                "28": `${PATH}/fire/fire_28_800x800.webm`,
                "29": `${PATH}/fire/fire_29_800x800.webm`,
                "30": `${PATH}/fire/fire_30_800x800.webm`,
                "31": `${PATH}/fire/fire_31_800x800.webm`,
                "32": `${PATH}/fire/fire_32_800x800.webm`,
                "33": `${PATH}/fire/fire_33_800x800.webm`,
                "35": `${PATH}/fire/fire_35_800x800.webm`,
                "36": `${PATH}/fire/fire_36_800x800.webm`,
                "37": `${PATH}/fire/fire_37_800x800.webm`,
                "38": `${PATH}/fire/fire_38_800x800.webm`,
                "39": `${PATH}/fire/fire_39_800x800.webm`,
                "40": `${PATH}/fire/fire_40_800x800.webm`,
                "41": `${PATH}/fire/fire_41_800x800.webm`,
                "43": `${PATH}/fire/fire_43_800x800.webm`,
                "45": `${PATH}/fire/fire_45_800x800.webm`,
                "47": `${PATH}/fire/fire_47_800x800.webm`,
                "49": `${PATH}/fire/fire_49_800x800.webm`,
                "51": `${PATH}/fire/fire_51_800x800.webm`,
                "53": `${PATH}/fire/fire_53_800x800.webm`,
                "55": `${PATH}/fire/fire_55_800x800.webm`,
                "57": `${PATH}/fire/fire_57_800x800.webm`,
                "59": `${PATH}/fire/fire_59_800x800.webm`,
                "61": `${PATH}/fire/fire_61_800x800.webm`,
                "63": `${PATH}/fire/fire_63_800x800.webm`,
                "65": `${PATH}/fire/fire_65_800x800.webm`,
                "110": `${PATH}/fire/fire_110_800x800.webm`,
                "112": `${PATH}/fire/fire_112_800x800.webm`,
                "114": `${PATH}/fire/fire_114_800x800.webm`,
                "116": `${PATH}/fire/fire_116_800x800.webm`,
                "118": `${PATH}/fire/fire_118_800x800.webm`,
                "120": `${PATH}/fire/fire_120_800x800.webm`,
                "ball": {
                    "01": `${PATH}/fire/fire_ball_CIRCLE_02.webm`,
                    "02": `${PATH}/fire/fire_ball_RECTANGLE_01.webm`,
                    "03": `${PATH}/fire/fire_ball_RECTANGLE_09.webm`,
                    "04": `${PATH}/fire/fire_ball_RECTANGLE_11.webm`,
                    "05": `${PATH}/fire/fire_ball_rotating_CIRCLE_01.webm`,
                },
                "blast": {
                    "01": `${PATH}/fire/fire_blast_RAY_01.webm`,
                    "02": `${PATH}/fire/fire_blast_RAY_02.webm`,
                    "03": `${PATH}/fire/fire_blast_RAY_03.webm`,
                    "04": `${PATH}/fire/fire_blast_SQUARE_01.webm`,
                },
                "bolt": `${PATH}/fire/fire_bolt_30ft_1600x400.webm`,
                "breath": `${PATH}/fire/fire_breath_CONE_01.webm`,
                "cone": `${PATH}/fire/fire_cone_CONE_01.webm`,
                "explosion": {
                    "01": `${PATH}/fire/fire_explosion_CIRCLE_01.webm`,
                    "02": `${PATH}/fire/fire_explosion_CIRCLE_02.webm`,
                    "03": `${PATH}/fire/fire_explosion_CIRCLE_03.webm`,
                    "04": `${PATH}/fire/fire_explosion_CIRCLE_04.webm`,
                    "05": `${PATH}/fire/fire_explosion_CIRCLE_05.webm`,
                    "06": `${PATH}/fire/fire_explosion_CIRCLE_06.webm`,
                    "07": `${PATH}/fire/fire_explosion_CIRCLE_07.webm`,
                    "08": `${PATH}/fire/fire_explosion_CIRCLE_08.webm`,
                    "09": `${PATH}/fire/fire_explosion_pheonix_SQUARE.webm`,
                },
                "ray": `${PATH}/fire/fire_ray_SQUARE_01.webm`,
                "ring": `${PATH}/fire/fire_ring_CIRCLE_01.webm`,
                "spiral": `${PATH}/fire/fire_spiral_CIRCLE_01.webm`,
                "wall": `${PATH}/fire/fire_wall_RECTANGLE_01.webm`,
                "wheel": `${PATH}/fire/fire_wheel_loop_CIRCLE.webm`,
            },
            "flash": {
                "01": `${PATH}/flash/flash_01_800x800.webm`,
                "03": `${PATH}/flash/flash_03_800x800.webm`,
                "05": `${PATH}/flash/flash_05_800x800.webm`,
                "07": `${PATH}/flash/flash_07_800x800.webm`,
                "09": `${PATH}/flash/flash_09_800x800.webm`,
                "11": `${PATH}/flash/flash_11_800x800.webm`,
                "13": `${PATH}/flash/flash_13_800x800.webm`,
                "15": `${PATH}/flash/flash_15_800x800.webm`,
                "17": `${PATH}/flash/flash_17_800x800.webm`,
                "19": `${PATH}/flash/flash_19_800x800.webm`,
                "21": `${PATH}/flash/flash_21_800x800.webm`,
                "23": `${PATH}/flash/flash_23_800x800.webm`,
                "25": `${PATH}/flash/flash_25_800x800.webm`,
            },
            "level 01": {
                "bless": {
                    "blue": `${PATH}/level 01/bless_blue_800x800.webm`,
                    "green": `${PATH}/level 01/bless_green_800x800.webm`,
                    "purple": `${PATH}/level 01/bless_purple_800x800.webm`,
                    "red": `${PATH}/level 01/bless_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/bless_yellow_800x800.webm`,
                },
                "burning hands": {
                    "green": `${PATH}/level 01/burning_hands_green.webm`,
                    "red": `${PATH}/level 01/burning_hands_red.webm`,

                },
                "charm person": `${PATH}/level 01/charm_person_800x800.webm`,
                "cd water": `${PATH}/level 01/create_or_destroy_water_800x800.webm`,
                "cure wounds": {
                    "blue": `${PATH}/level 01/cure_wounds_blue_800x800.webm`,
                    "green": `${PATH}/level 01/cure_wounds_green_800x800.webm`,
                    "purple": `${PATH}/level 01/cure_wounds_purple_800x800.webm`,
                    "red": `${PATH}/level 01/cure_wounds_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/cure_wounds_yellow_800x800.webm`,
                },
                "detect magic": {
                    "blue": `${PATH}/level 01/detect_magic_blue_800x800.webm`,
                    "green": `${PATH}/level 01/detect_magic_green_800x800.webm`,
                    "purple": `${PATH}/level 01/detect_magic_purple_800x800.webm`,
                    "red": `${PATH}/level 01/detect_magic_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/detect_magic_yellow_800x800.webm`,
                },
                "divine favour": {
                    "blue": `${PATH}/level 01/divine_favor_blue_800x800.webm`,
                    "green": `${PATH}/level 01/divine_favor_green_800x800.webm`,
                    "purple": `${PATH}/level 01/divine_favor_purple_800x800.webm`,
                    "red": `${PATH}/level 01/divine_favor_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/divine_favor_yellow_800x800.webm`,
                },
                "fog cloud": {
                    "blue": `${PATH}/level 01/fog_cloud_blue_800x800.webm`,
                    "green": `${PATH}/level 01/fog_cloud_green_800x800.webm`,
                    "purple": `${PATH}/level 01/fog_cloud_purple_800x800.webm`,
                    "red": `${PATH}/level 01/fog_cloud_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/fog_cloud_yellow_800x800.webm`,
                },
                "guiding bolt": {
                    "05ft": `${PATH}/level 01/guiding_bolt_5ft.webm`,
                    "15ft": `${PATH}/level 01/guiding_bolt_15ft.webm`,
                    "30ft": `${PATH}/level 01/guiding_bolt_30ft.webm`,
                    "60ft": `${PATH}/level 01/guiding_bolt_60ft.webm`,
                    "90ft": `${PATH}/level 01/guiding_bolt_90ft.webm`,
                },
                "healing word": {
                    "blue": `${PATH}/level 01/healing_word_blue_800x800.webm`,
                    "green": `${PATH}/level 01/healing_word_green_800x800.webm`,
                    "purple": `${PATH}/level 01/healing_word_purple_800x800.webm`,
                    "red": `${PATH}/level 01/healing_word_red_800x800.webm`,
                    "yellow": `${PATH}/level 01/healing_word_yellow_800x800.webm`,
                },
                "thuderwave": {
                    "blue": `${PATH}/level 01/thunderwave_blue_15ft.webm`,
                    "green": `${PATH}/level 01/thunderwave_green_15ft.webm`,
                    "purple": `${PATH}/level 01/thunderwave_purple_15ft.webm`,
                    "red": `${PATH}/level 01/thunderwave_red_15ft.webm`,
                    "yellow": `${PATH}/level 01/thunderwave_yellow_15ft.webm`,
                },
            },
            "level 02": {
                "aganazzar": `${PATH}/level 02/aganazzar's_scorcher_30ft.webm`,
                "air bubble": `${PATH}/level 02/air_bubble_800x800.webm`,
                "continual flame": `${PATH}/level 02/continual_flame_800x800.webm`,
                "darkness": `${PATH}/level 02/darkness_800x800.webm`,
                "flaming sphere": `${PATH}/level 02/flaming_sphere_800x800.webm`,
                "misty step": `${PATH}/level 02/misty_step_800x800.webm`,
            },
            "magic": {
                "aura": `${PATH}/magic/magic_chaotic_curves_RECTANGLE_01.webm`,
                "chaotic curves": `${PATH}/magic/magic_chaotic_curves_RECTANGLE_01.webm`,
                "explosion": {
                    "01": `${PATH}/magic/magic_explosion_symbol_CIRCLE.webm`,
                    "02": `${PATH}/magic/magic_explosion_symbol_CIRCLE_02.webm`,
                },
                "gloop": {
                    "01": `${PATH}/magic/magic_gloop_RECTANGLE_01.webm`,
                    "02": `${PATH}/magic/magic_gloop_RECTANGLE_02.webm`,
                },
                "helix": `${PATH}/magic/helix_RECTANGLE_01.webm`,
                "impact": {
                    "01": `${PATH}/magic/magic_impact_SQUARE_01.webm`,
                    "02": `${PATH}/magic/magic_impact_SQUARE_02.webm`,
                    "03": `${PATH}/magic/magic_impact_SQUARE_03.webm`,
                },
                "sphere": `${PATH}/magic/magic_sphere_1token_SQUARE.webm`,
                "impact": {
                    "01": `${PATH}/magic/magic_impact_SQUARE_01.webm`,
                    "02": `${PATH}/magic/magic_impact_SQUARE_02.webm`,
                    "03": `${PATH}/magic/magic_impact_SQUARE_03.webm`,
                },
                "mind sliver": `${PATH}/magic/mind_sliver_LINE.webm`,
                "portal": {
                    "blue": `${PATH}/magic/portal_square_blue_SQUARE.webm`,
                    "green": `${PATH}/magic/portal_square_green_SQUARE.webm`,
                    "purple": `${PATH}/magic/portal_square_purple_SQUARE.webm`,
                    "red": `${PATH}/magic/portal_square_red_SQUARE.webm`,
                    "yellow": `${PATH}/magic/portal_square_yellow_SQUARE.webm`,
                },
                "swish": {
                    "01": `${PATH}/magic/magic_swish_RECTANGLE_01.webm`,
                    "02": `${PATH}/magic/magic_swish_SQUARE_01.webm`,
                    "03": `${PATH}/magic/magic_swish_SQUARE_02.webm`,
                    "04": `${PATH}/magic/magic_swish_SQUARE_03.webm`,
                    "05": `${PATH}/magic/magic_swish_SQUARE_04.webm`,
                    "06": `${PATH}/magic/magic_swish_SQUARE_05.webm`,
                },
            },
            "misc": {
                "all seeing eye": `${PATH}/misc/all_seeing_eye_RECTANGLE.webm`,
                "blood splatter": `${PATH}/misc/blood_splatter_CIRCLE_01.webm`,
                "charm": `${PATH}/misc/charm_CIRCLE_01.webm`,
                "cool cat": `${PATH}/misc/cool_cat_800x800.webm`,
                "skull": `${PATH}/misc/crazy_death_skull_SQUARE.webm`,
                "demon": `${PATH}/misc/demon_face_SQUARE.webm`,
                "fiery eyes": {
                    "01": `${PATH}/misc/fiery_eyes_SQUARE_01.webm`,
                    "02": `${PATH}/misc/fiery_eyes_SQUARE_02.webm`,
                    "03": `${PATH}/misc/fiery_eyes_SQUARE_03.webm`,
                    "04": `${PATH}/misc/fiery_eyes_SQUARE_04.webm`,
                    "05": `${PATH}/misc/fiery_eyes_SQUARE_05.webm`,
                },
                "firewwork": `${PATH}/misc/firework_CIRCLE.webm`,
                "heart": {
                    "blue": `${PATH}/misc/heart_blue_SQUARE.webm`,
                    "green": `${PATH}/misc/heart_green_SQUARE.webm`,
                    "purple": `${PATH}/misc/heart_purple_SQUARE.webm`,
                    "red": `${PATH}/misc/heart_red_SQUARE.webm`,
                    "yellow": `${PATH}/misc/heart_yellow_SQUARE.webm`,
                },
                "symbol": {
                    "01": `${PATH}/misc/magic_symbol_SQUARE_01.webm`,
                    "02": `${PATH}/misc/magic_symbol_SQUARE_02.webm`,
                    "03": `${PATH}/misc/magic_symbol_SQUARE_03.webm`,
                    "04": `${PATH}/misc/magic_symbol_SQUARE_04.webm`,
                    "05": `${PATH}/misc/magic_symbol_SQUARE_05.webm`,
                },
                "mend": `${PATH}/misc/mend_SQUARE_01.webm`,
                "music": {
                    "01": `${PATH}/misc/music_RECTANGLE.webm`,
                    "02": `${PATH}/misc/music_SQUARE_01.webm`,
                },
                "spark": `${PATH}/misc/repeating_spark_CIRCLE_01.webm`,
                "skeleton": `${PATH}/misc/shakey_skeleton_SQUARE_01.webm`,
                "weird": {
                    "01": `${PATH}/misc/weird_SQUARE_01.webm`,
                    "02": `${PATH}/misc/weird_SQUARE_02.webm`,
                },
            },
            "mix": {
                "air lightning": `${PATH}/mix/air_lightning_water_SQUARE_01.webm`,
                "all blast": `${PATH}/mix/all_blast_SQUARE_01.webm`,
                "all blast": `${PATH}/mix/all_blast_SQUARE_01.webm`,
                "bats": `${PATH}/mix/bats_at_camera_SQUARE.webm`,
                "electric ball": {
                    "01": `${PATH}/mix/electric_ball_CIRCLE_02.webm`,
                    "02": `${PATH}/mix/electric_ball_CIRCLE_09.webm`,
                    "03": `${PATH}/mix/electric_ball_CIRCLE_10.webm`,

                },
                "electricity": `${PATH}/mix/ectricity_SQUARE_01.webm`,
                "embers": {
                    "01": `${PATH}/mix/embers_CIRCLE_02.webm`,
                    "02": `${PATH}/mix/embers_CIRCLE_04.webm`,
                },
                
                "energy fire": `${PATH}/mix/energy_fire_shot_SQUARE_01.webm`,
                "fire earth explosion": {
                    "01": `${PATH}/mix/fire_earth_explosion_CIRCLE_01.webm`,
                    "02": `${PATH}/mix/fire_earth_explosion_SQUARE_03.webm`,
                    "03": `${PATH}/mix/fire_earth_explosion_SQUARE_04.webm`,
                    "04": `${PATH}/mix/fire_earth_explosion_SQUARE_05.webm`,
                    "05": `${PATH}/mix/fire_earth_explosion_SQUARE_06.webm`,
                    "06": `${PATH}/mix/fire_earth_explosion_SQUARE_07.webm`,
                },
                "fire lightning bolt": `${PATH}/mix/fire_lightning_bolt_RAY_01.webm`,
                "fire lightning smoke": {
                    "01": `${PATH}/mix/fire_lightning_smoke_trails_explosion_SQUARE_01.webm`,
                    "02": `${PATH}/mix/fire_smoke_explosion_SQUARE_01.webm`,                    
                },
                "fire water swirl": `${PATH}/mix/fire_water_swirl_CIRCLE_01.webm`,
                "four element strike": `${PATH}/mix/four_element_strike_SQUARE_01.webm`,
                "lightning smash": {
                    "01": `${PATH}/mix/lightning_earth_smash_RAY_02.webm`,
                    "02": `${PATH}/mix/lightning_earth_smash_SQUARE_01.webm`,
                    "03": `${PATH}/mix/lightning_water_bolt_SQUARE.webm`,
                },
                
                "water": {
                    "01": `${PATH}/mix/water_energy_electric_swirl_CIRCLE_01.webm`,
                    "02": `${PATH}/mix/water_energy_swirl_RAY_01.webm`,
                },
            },
            "simple": {
                "01": `${PATH}/simple/simple_001_800x800.webm`,
                "03": `${PATH}/simple/simple_003_800x800.webm`,
                "05": `${PATH}/simple/simple_005_800x800.webm`,
                "07": `${PATH}/simple/simple_007_800x800.webm`,
                "09": `${PATH}/simple/simple_009_800x800.webm`,
                "11": `${PATH}/simple/simple_011_800x800.webm`,
                "13": `${PATH}/simple/simple_013_800x800.webm`,
                "15": `${PATH}/simple/simple_015_800x800.webm`,
                "17": `${PATH}/simple/simple_017_800x800.webm`,
                "19": `${PATH}/simple/simple_019_800x800.webm`,
                "21": `${PATH}/simple/simple_021_800x800.webm`,
                "23": `${PATH}/simple/simple_023_800x800.webm`,
                "25": `${PATH}/simple/simple_025_800x800.webm`,
                "27": `${PATH}/simple/simple_027_800x800.webm`,
                "29": `${PATH}/simple/simple_029_800x800.webm`,
                "31": `${PATH}/simple/simple_031_800x800.webm`,
                "33": `${PATH}/simple/simple_033_800x800.webm`,
                "35": `${PATH}/simple/simple_035_800x800.webm`,
                "37": `${PATH}/simple/simple_037_800x800.webm`,
                "39": `${PATH}/simple/simple_039_800x800.webm`,
                "41": `${PATH}/simple/simple_041_800x800.webm`,
                "43": `${PATH}/simple/simple_043_800x800.webm`,
                "45": `${PATH}/simple/simple_045_800x800.webm`,
                "47": `${PATH}/simple/simple_047_800x800.webm`,
                "49": `${PATH}/simple/simple_049_800x800.webm`,
                "51": `${PATH}/simple/simple_051_800x800.webm`,
                "53": `${PATH}/simple/simple_053_800x800.webm`,
                "55": `${PATH}/simple/simple_055_800x800.webm`,
                "57": `${PATH}/simple/simple_057_800x800.webm`,
                "59": `${PATH}/simple/simple_059_800x800.webm`,
                "61": `${PATH}/simple/simple_061_800x800.webm`,
                "63": `${PATH}/simple/simple_063_800x800.webm`,
                "65": `${PATH}/simple/simple_065_800x800.webm`,
                "67": `${PATH}/simple/simple_067_800x800.webm`,
                "69": `${PATH}/simple/simple_069_800x800.webm`,
                "71": `${PATH}/simple/simple_071_800x800.webm`,
                "73": `${PATH}/simple/simple_073_800x800.webm`,
                "75": `${PATH}/simple/simple_075_800x800.webm`,
                "77": `${PATH}/simple/simple_077_800x800.webm`,
                "79": `${PATH}/simple/simple_079_800x800.webm`,
                "81": `${PATH}/simple/simple_081_800x800.webm`,
                "83": `${PATH}/simple/simple_083_800x800.webm`,
                "85": `${PATH}/simple/simple_085_800x800.webm`,
                "87": `${PATH}/simple/simple_087_800x800.webm`,
                "89": `${PATH}/simple/simple_089_800x800.webm`,
                "91": `${PATH}/simple/simple_091_800x800.webm`,
                "93": `${PATH}/simple/simple_093_800x800.webm`,
                "95": `${PATH}/simple/simple_095_800x800.webm`,
                "97": `${PATH}/simple/simple_097_800x800.webm`,
                "99": `${PATH}/simple/simple_099_800x800.webm`,
                "101": `${PATH}/simple/simple_101_800x800.webm`,
                "103": `${PATH}/simple/simple_103_800x800.webm`,
                "105": `${PATH}/simple/simple_105_800x800.webm`,
                "107": `${PATH}/simple/simple_107_800x800.webm`,
                "109": `${PATH}/simple/simple_109_800x800.webm`,
                "111": `${PATH}/simple/simple_111_800x800.webm`,
                "113": `${PATH}/simple/simple_113_800x800.webm`,
                "115": `${PATH}/simple/simple_115_800x800.webm`,
                "117": `${PATH}/simple/simple_117_800x800.webm`,
            },
            "smoke": {
                "01": `${PATH}/smoke/smoke_001_800x800.webm`,
                "03": `${PATH}/smoke/smoke_003_800x800.webm`,
                "05": `${PATH}/smoke/smoke_005_800x800.webm`,
                "07": `${PATH}/smoke/smoke_007_800x800.webm`,
                "09": `${PATH}/smoke/smoke_009_800x800.webm`,
                "11": `${PATH}/smoke/smoke_011_800x800.webm`,
                "13": `${PATH}/smoke/smoke_013_800x800.webm`,
                "15": `${PATH}/smoke/smoke_015_800x800.webm`,
                "17": `${PATH}/smoke/smoke_017_800x800.webm`,
                "19": `${PATH}/smoke/smoke_019_800x800.webm`,
                "21": `${PATH}/smoke/smoke_021_800x800.webm`,
                "23": `${PATH}/smoke/smoke_023_800x800.webm`,
                "25": `${PATH}/smoke/smoke_025_800x800.webm`,
                "27": `${PATH}/smoke/smoke_027_800x800.webm`,
                "29": `${PATH}/smoke/smoke_029_800x800.webm`,
                "31": `${PATH}/smoke/smoke_031_800x800.webm`,
                "33": `${PATH}/smoke/smoke_033_800x800.webm`,
                "35": `${PATH}/smoke/smoke_035_800x800.webm`,
                "37": `${PATH}/smoke/smoke_037_800x800.webm`,
                "39": `${PATH}/smoke/smoke_039_800x800.webm`,
                "41": `${PATH}/smoke/smoke_041_800x800.webm`,
                "43": `${PATH}/smoke/smoke_043_800x800.webm`,
                "45": `${PATH}/smoke/smoke_045_800x800.webm`,
                "47": `${PATH}/smoke/smoke_047_800x800.webm`,
                "49": `${PATH}/smoke/smoke_049_800x800.webm`,
                "51": `${PATH}/smoke/smoke_051_800x800.webm`,
                "53": `${PATH}/smoke/smoke_053_800x800.webm`,
                "55": `${PATH}/smoke/smoke_055_800x800.webm`,
                "57": `${PATH}/smoke/smoke_057_800x800.webm`,
                "59": `${PATH}/smoke/smoke_059_800x800.webm`,
                "61": `${PATH}/smoke/smoke_061_800x800.webm`,
                "63": `${PATH}/smoke/smoke_063_800x800.webm`,
                "65": `${PATH}/smoke/smoke_065_800x800.webm`,
                "67": `${PATH}/smoke/smoke_067_800x800.webm`,
                "69": `${PATH}/smoke/smoke_069_800x800.webm`,
                "71": `${PATH}/smoke/smoke_071_800x800.webm`,
                "73": `${PATH}/smoke/smoke_073_800x800.webm`,
                "75": `${PATH}/smoke/smoke_075_800x800.webm`,
                "77": `${PATH}/smoke/smoke_077_800x800.webm`,
                "79": `${PATH}/smoke/smoke_079_800x800.webm`,
                "81": `${PATH}/smoke/smoke_081_800x800.webm`,
                "83": `${PATH}/smoke/smoke_083_800x800.webm`,
                "85": `${PATH}/smoke/smoke_085_800x800.webm`,
                "87": `${PATH}/smoke/smoke_087_800x800.webm`,
                "89": `${PATH}/smoke/smoke_089_800x800.webm`,
                "91": `${PATH}/smoke/smoke_091_800x800.webm`,
                "93": `${PATH}/smoke/smoke_093_800x800.webm`,
                "95": `${PATH}/smoke/smoke_095_800x800.webm`,
                "97": `${PATH}/smoke/smoke_097_800x800.webm`,
                "99": `${PATH}/smoke/smoke_099_800x800.webm`,
                "101": `${PATH}/smoke/smoke_101_800x800.webm`,
                "103": `${PATH}/smoke/smoke_103_800x800.webm`,
                "105": `${PATH}/smoke/smoke_105_800x800.webm`,
                "107": `${PATH}/smoke/smoke_107_800x800.webm`,
                "109": `${PATH}/smoke/smoke_109_800x800.webm`,
                "111": `${PATH}/smoke/smoke_111_800x800.webm`,
                "113": `${PATH}/smoke/smoke_113_800x800.webm`,
                "115": `${PATH}/smoke/smoke_115_800x800.webm`,
                "117": `${PATH}/smoke/smoke_117_800x800.webm`,
                "119": `${PATH}/smoke/smoke_119_800x800.webm`,
                "121": `${PATH}/smoke/smoke_121_800x800.webm`,
            },
            "water": {
                "01": `${PATH}/water/liquid_001_800x800.webm`,
                "03": `${PATH}/water/liquid_003_800x800.webm`,
                "05": `${PATH}/water/liquid_005_800x800.webm`,
                "07": `${PATH}/water/liquid_007_800x800.webm`,
                "09": `${PATH}/water/liquid_009_800x800.webm`,
                "11": `${PATH}/water/liquid_011_800x800.webm`,
                "13": `${PATH}/water/liquid_013_800x800.webm`,
                "15": `${PATH}/water/liquid_015_800x800.webm`,
                "17": `${PATH}/water/liquid_017_800x800.webm`,
                "19": `${PATH}/water/liquid_019_800x800.webm`,
                "21": `${PATH}/water/liquid_021_800x800.webm`,
                "23": `${PATH}/water/liquid_023_800x800.webm`,
                "25": `${PATH}/water/liquid_025_800x800.webm`,
                "27": `${PATH}/water/liquid_027_800x800.webm`,
                "29": `${PATH}/water/liquid_029_800x800.webm`,
                "31": `${PATH}/water/liquid_031_800x800.webm`,
                "33": `${PATH}/water/liquid_033_800x800.webm`,
                "35": `${PATH}/water/liquid_035_800x800.webm`,
                "37": `${PATH}/water/liquid_037_800x800.webm`,
                "39": `${PATH}/water/liquid_039_800x800.webm`,
                "41": `${PATH}/water/liquid_041_800x800.webm`,
                "43": `${PATH}/water/liquid_043_800x800.webm`,
                "45": `${PATH}/water/liquid_045_800x800.webm`,
                "47": `${PATH}/water/liquid_047_800x800.webm`,
                "49": `${PATH}/water/liquid_049_800x800.webm`,
                "51": `${PATH}/water/liquid_051_800x800.webm`,
                "53": `${PATH}/water/liquid_053_800x800.webm`,
                "55": `${PATH}/water/liquid_055_800x800.webm`,
                "57": `${PATH}/water/liquid_057_800x800.webm`,
                "59": `${PATH}/water/liquid_059_800x800.webm`,
                "61": `${PATH}/water/liquid_061_800x800.webm`,
                "63": `${PATH}/water/liquid_063_800x800.webm`,
                "65": `${PATH}/water/liquid_065_800x800.webm`,
                "67": `${PATH}/water/liquid_067_800x800.webm`,
                "69": `${PATH}/water/liquid_069_800x800.webm`,
                "71": `${PATH}/water/liquid_071_800x800.webm`,
                "73": `${PATH}/water/liquid_073_800x800.webm`,
                "75": `${PATH}/water/liquid_075_800x800.webm`,
                "77": `${PATH}/water/liquid_077_800x800.webm`,
                "79": `${PATH}/water/liquid_079_800x800.webm`,
                "81": `${PATH}/water/liquid_081_800x800.webm`,
                "83": `${PATH}/water/liquid_083_800x800.webm`,
                "85": `${PATH}/water/liquid_085_800x800.webm`,
                "87": `${PATH}/water/liquid_087_800x800.webm`,
                "89": `${PATH}/water/liquid_089_800x800.webm`,
                "91": `${PATH}/water/liquid_091_800x800.webm`,
                "93": `${PATH}/water/liquid_093_800x800.webm`,
                "95": `${PATH}/water/liquid_095_800x800.webm`,
                "97": `${PATH}/water/liquid_097_800x800.webm`,
                "99": `${PATH}/water/liquid_099_800x800.webm`,
                "101": `${PATH}/water/liquid_101_800x800.webm`,
                "103": `${PATH}/water/liquid_103_800x800.webm`,
                "105": `${PATH}/water/liquid_105_800x800.webm`,
                "107": `${PATH}/water/liquid_107_800x800.webm`,
                "109": `${PATH}/water/liquid_109_800x800.webm`,
                "111": `${PATH}/water/liquid_111_800x800.webm`,
                "113": `${PATH}/water/liquid_113_800x800.webm`,
                "115": `${PATH}/water/liquid_115_800x800.webm`,
                "117": `${PATH}/water/liquid_117_800x800.webm`,
                "119": `${PATH}/water/liquid_119_800x800.webm`,
                "121": `${PATH}/water/liquid_121_800x800.webm`,
                "acid splash": {
                    "01": `${PATH}/water/acid_splash_800x800.webm`,
                    "02": `${PATH}/water/acid_splash_CIRCLE_02.webm`,
                },
                "ball": `${PATH}/water/water_ball_CIRCLE_01.webm`,
                "create": {
                    "01": `${PATH}/water/create_water_CIRCLE_01.webm`,
                    "02": `${PATH}/water/create_water_CIRCLE_02.webm`,
                },
                "ice blast": `${PATH}/water/ice_blast_RECTANGLE_01.webm`,
                "splash": `${PATH}/water/water-splash_RECTANGLE_01.webm`,
                "water blast": {
                    "01": `${PATH}/water/water_blast_RAY_01.webm`,
                    "02": `${PATH}/water/water_blast_RAY_02.webm`,
                },
                "water impact": `${PATH}/water/water_impact_SQUARE_01.webm`,
                "water splash": {
                    "01": `${PATH}/water/water_splash_SQUARE_01.webm`,
                    "02": `${PATH}/water/water_splash_SQUARE_02.webm`,
                },
                "water wall": `${PATH}/water/water_wall_RECTANGLE_01.webm`,
            },
        };
        Sequencer.Database.registerEntries('animated-spell-effects-cartoon', cartoonDatabase);
    
});
