Hooks.once('ready', () => {
    if (game.modules.get("sequencer")?.active) {
        const PATH = "modules/animated-spell-effects-cartoon/spell-effects/cartoon";
        const cartoonDatabase = {
            "air": {
                "blast": {
                    "circle": `${PATH}/air/air_blast_CIRCLE_01.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_01.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_02.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_03.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_04.webm`,
                    "cone": `${PATH}/air/air_blast_CONE_05.webm`,
                },
                "bolt": {
                    "ray": `${PATH}/air/air_bolt_RAY_01.webm`,
                    "square": `${PATH}/air/air_bolt_SQUARE_01.webm`,
                    "square": `${PATH}/air/air_bolt_SQUARE_02.webm`,
                },
                "explosion": {
                    "gray": `${PATH}/air/air_explosion_800x800.webm`,
                    "blue": `${PATH}/air/air_explosion_blue_800x800.webm`,
                    "green": `${PATH}/air/air_explosion_green_800x800.webm`,
                    "purple": `${PATH}/air/air_explosion_purple_800x800.webm`,
                    "red": `${PATH}/air/air_explosion_red_800x800.webm`,
                    "yellow": `${PATH}/air/air_explosion_yellow_800x800.webm`,
                },
                "gust": {
                    "gray": `${PATH}/air/air_gust_800x800.webm`,
                    "blue": `${PATH}/air/air_gust_blue_800x800.webm`,
                    "green": `${PATH}/air/air_gust_green_800x800.webm`,
                    "purple": `${PATH}/air/air_gust_purple_800x800.webm`,
                    "red": `${PATH}/air/air_gust_red_800x800.webm`,
                    "square": `${PATH}/air/air_gust_SQUARE_01.webm`,
                    "yellow": `${PATH}/air/air_gust_yellow_800x800.webm`,
                },
                "infinity": `${PATH}/air/air_infinity_RECTANGLE_01.webm`,
                "portal": `${PATH}/air/air_portal_CIRCLE_01.webm`,
                "puff": {
                    "01": `${PATH}/air/air_puff_CIRCLE_01.webm`,
                    "02": `${PATH}/air/air_puff_CIRCLE_02.webm`,
                    "03": `${PATH}/air/air_puff_CIRCLE_03.webm`,
                },
                "spiral": {
                    "gray": `${PATH}/air/air_spiral_800x800.webm`,
                    "blue": `${PATH}/air/air_spiral_blue_800x800.webm`,
                    "green": `${PATH}/air/air_spiral_green_800x800.webm`,
                    "purple": `${PATH}/air/air_spiral_purple_800x800.webm`,
                    "red": `${PATH}/air/air_spiral_red_800x800.webm`,
                    "yellow": `${PATH}/air/air_spiral_yellow_800x800.webm`,
                },
                "wall": `${PATH}/air/air_wall_SQUARE_01.webm`,
            },
            "cantrips": {
                "acid_splash": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/acid_splash_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/acid_splash_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/acid_splash_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/acid_splash_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/acid_splash_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/acid_splash_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/acid_splash_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/acid_splash_yellow_90ft.webm`,
                    },
                },
                "eldritch_blast": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/eldritch_blast_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/eldritch_blast_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/eldritch_blast_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/eldritch_blast_yellow_90ft.webm`,
                    },
                },
                "fire_bolt": {
                    "blue": {
                        "15ft": `${PATH}/cantrips/fire_bolt_blue_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_blue_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_blue_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_blue_90ft.webm`,
                    },
                    "green": {
                        "15ft": `${PATH}/cantrips/fire_bolt_green_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_green_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_green_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_green_90ft.webm`,
                    },
                    "purple": {
                        "15ft": `${PATH}/cantrips/fire_bolt_purple_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_purple_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_purple_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_purple_90ft.webm`,
                    },
                    "red": {
                        "15ft": `${PATH}/cantrips/fire_bolt_red_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_red_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_red_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_red_90ft.webm`,
                    },
                    "yellow": {
                        "15ft": `${PATH}/cantrips/fire_bolt_yellow_15ft.webm`,
                        "30ft": `${PATH}/cantrips/fire_bolt_yellow_30ft.webm`,
                        "60ft": `${PATH}/cantrips/fire_bolt_yellow_60ft.webm`,
                        "90ft": `${PATH}/cantrips/fire_bolt_yellow_90ft.webm`,
                    },
                },
                "frostbite": `${PATH}/cantrips/gust_800x800.webm`, 
                "gust": {
                    "15ft": `${PATH}/cantrips/gust_15ft.webm`, 
                    "800x800": `${PATH}/cantrips/gust_800x800.webm`,
                },
                "lightning_lure": {
                    "blue": `${PATH}/cantrips/lightning_lure_blue_15ft.webm`,
                    "green": `${PATH}/cantrips/lightning_lure_green_15ft.webm`,
                    "purple": `${PATH}/cantrips/lightning_lure_purple_15ft.webm`,
                    "red": `${PATH}/cantrips/lightning_lure_red_15ft.webm`,
                    "yellow": `${PATH}/cantrips/lightning_lure_yellow_15ft.webm`,
                },
                "mending": {
                    "blue": `${PATH}/cantrips/mending_blue_800x800.webm`,
                    "green": `${PATH}/cantrips/mending_green_800x800.webm`,
                    "purple": `${PATH}/cantrips/mending_purple_800x800.webm`,
                    "red": `${PATH}/cantrips/mending_red_800x800.webm`,
                    "yellow": `${PATH}/cantrips/mending_yellow_800x800.webm`,
                },
                "poison_spray": {
                    "blue": `${PATH}/cantrips/poison_spray_blue_10ft.webm`,
                    "green": `${PATH}/cantrips/poison_spray_green_10ft.webm`,
                    "purple": `${PATH}/cantrips/poison_spray_purple_10ft.webm`,
                    "red": `${PATH}/cantrips/poison_spray_red_10ft.webm`,
                    "yellow": `${PATH}/cantrips/poison_spray_yellow_10ft.webm`,
                },
                "ray_of_frost": {
                    "05ft": `${PATH}/cantrips/ray_of_frost_5ft.webm`,
                    "15ft": `${PATH}/cantrips/ray_of_frost_15ft.webm`,
                    "30ft": `${PATH}/cantrips/ray_of_frost_30ft.webm`,
                    "60ft": `${PATH}/cantrips/ray_of_frost_60ft.webm`,
                },
                "sacred_flame": {
                    "blue": `${PATH}/cantrips/sacred_flame_blue_800x800.webm`,
                    "green": `${PATH}/cantrips/sacred_flame_green_800x800.webm`,
                    "purple": `${PATH}/cantrips/sacred_flame_purple_800x800.webm`,
                    "red": `${PATH}/cantrips/sacred_flame_red_800x800.webm`,
                    "yellow": `${PATH}/cantrips/sacred_flame_yellow_800x800.webm`,
                },
                "shocking_grasp": {
                    "blue": `${PATH}/cantrips/shocking_grasp_blue_5ft.webm`,
                    "green": `${PATH}/cantrips/shocking_grasp_green_5ft.webm`,
                    "purple": `${PATH}/cantrips/shocking_grasp_purple_5ft.webm`,
                    "red": `${PATH}/cantrips/shocking_grasp_red_5ft.webm`,
                    "yellow": `${PATH}/cantrips/shocking_grasp_yellow_5ft.webm`,
                },
            },
            "conditions": {
                "blinded": `${PATH}/conditions/condition_blinded_800x800.webm`,
                "charmed": `${PATH}/conditions/condition_charmed_800x800.webm`,
                "deafened": `${PATH}/conditions/condition_deafened_800x800.webm`,
                "exhaustion": `${PATH}/conditions/condition_exhaustion_800x800.webm`,
                "frightened": `${PATH}/conditions/condition_frightened_800x800.webm`,
                "grappled": `${PATH}/conditions/condition_grappled_800x800.webm`,
                "incapacitated": `${PATH}/conditions/condition_incapacitated_800x800.webm`,
                "invisible": `${PATH}/conditions/condition_invisible_800x800.webm`,
                "paralyzed": `${PATH}/conditions/condition_paralyzed_800x800.webm`,
                "petrified": `${PATH}/conditions/condition_petrified_800x800.webm`,
                "poisoned": `${PATH}/conditions/condition_poisoned_800x800.webm`,
                "prone": `${PATH}/conditions/condition_prone_800x800.webm`,
                "restrained": `${PATH}/conditions/condition_restrained_800x800.webm`,
                "stunned": `${PATH}/conditions/condition_stunned_800x800.webm`,
                "unconcious": `${PATH}/conditions/condition_unconcious_800x800.webm`,
            },
            "earth": {
                "debris": {
                    "01": `${PATH}/earth/debris_01_800x800.webm`,
                    "02": `${PATH}/earth/debris_02_800x800.webm`,
                    "03": `${PATH}/earth/debris_03_800x800.webm`,
                    "04": `${PATH}/earth/debris_04_800x800.webm`,
                    "05": `${PATH}/earth/debris_05_800x800.webm`,
                },
                "crack": `${PATH}/earth/earth_crack_SQUARE_01.webm`,
                "explosion": {
                    "01": `${PATH}/earth/earth_explosion_SQUARE_01.webm`,
                    "02": `${PATH}/earth/earth_explosion_SQUARE_02.webm`,
                    "03": `${PATH}/earth/earth_explosion_SQUARE_03.webm`,
                },
                "slam": `${PATH}/earth/earth_slam_RECTANGLE_01.webm`,
                "spike": `${PATH}/earth/earth_spike_CIRCLE_01.webm`,
                "plant": {
                    "growing01": `${PATH}/earth/plant_growing_SQUARE_01.webm`,
                    "growing02": `${PATH}/earth/plant_growing_SQUARE_01.webm`,
                },
            },
            "electricity": {
                "01": `${PATH}/electricity/electricity_01_800x800.webm`,
                "02": `${PATH}/electricity/electricity_02_800x800.webm`,
                "03": `${PATH}/electricity/electricity_03_800x800.webm`,
                "04": `${PATH}/electricity/electricity_04_800x800.webm`,
                "05": `${PATH}/electricity/electricity_05_800x800.webm`,
                "06": `${PATH}/electricity/electricity_06_800x800.webm`,
                "07": `${PATH}/electricity/electricity_07_800x800.webm`,
                "08": `${PATH}/electricity/electricity_08_800x800.webm`,
                "09": `${PATH}/electricity/electricity_09_800x800.webm`,
                "10": `${PATH}/electricity/electricity_10_800x800.webm`,
                "15": `${PATH}/electricity/electricity_15_800x800.webm`,
                "16": `${PATH}/electricity/electricity_16_800x800.webm`,
                "17": `${PATH}/electricity/electricity_17_800x800.webm`,
                "18": `${PATH}/electricity/electricity_18_800x800.webm`,
                "19": `${PATH}/electricity/electricity_19_800x800.webm`,
                "20": `${PATH}/electricity/electricity_20_800x800.webm`,
                "21": `${PATH}/electricity/electricity_21_800x800.webm`,
                "22": `${PATH}/electricity/electricity_22_800x800.webm`,
                "23": `${PATH}/electricity/electricity_23_800x800.webm`,
                "24": `${PATH}/electricity/electricity_24_800x800.webm`,
                "25": `${PATH}/electricity/electricity_25_800x800.webm`,
                "26": `${PATH}/electricity/electricity_26_800x800.webm`,
                "27": `${PATH}/electricity/electricity_27_800x800.webm`,
                "28": `${PATH}/electricity/electricity_28_800x800.webm`,
                "29": `${PATH}/electricity/electricity_29_800x800.webm`,
                "30": `${PATH}/electricity/electricity_30_800x800.webm`,
                "31": `${PATH}/electricity/electricity_31_800x800.webm`,
                "32": `${PATH}/electricity/electricity_32_800x800.webm`,
                "33": `${PATH}/electricity/electricity_33_800x800.webm`,
                "34": `${PATH}/electricity/electricity_34_800x800.webm`,
                "35": `${PATH}/electricity/electricity_35_800x800.webm`,
                "36": `${PATH}/electricity/electricity_36_800x800.webm`,
                "37": `${PATH}/electricity/electricity_37_800x800.webm`,
                "blast": {
                  "01": `${PATH}/electricity/electricity_blast_CIRCLE.webm`,
                  "02": `${PATH}/electricity/electric_blast_01.webm`,
                  "03": `${PATH}/electricity/electric_blast_RECTANGLE_02.webm`,
                  "04": `${PATH}/electricity/electrivity_blast_CIRCLE.webm`,
                },
                "pulse": `${PATH}/electricity/electricity_pulse_CIRCLE_01.webm`,
                "ball": {
                    "01": `${PATH}/electricity/electric_ball_CIRCLE_01.webm`,
                    "03": `${PATH}/electricity/electric_ball_CIRCLE_03.webm`,
                    "04": `${PATH}/electricity/electric_ball_CIRCLE_04.webm`,
                    "05": `${PATH}/electricity/electric_ball_CIRCLE_05.webm`,
                    "06": `${PATH}/electricity/electric_ball_CIRCLE_06.webm`,
                    "07": `${PATH}/electricity/electric_ball_CIRCLE_07.webm`,
                    "08": `${PATH}/electricity/electric_ball_CIRCLE_08.webm`,
                },
                "discharge": {
                    "01": `${PATH}/electricity/electric_discharge_CIRCLE_07.webm`,
                    "02": `${PATH}/electricity/electric_discharge_RECTANGLE_02.webm`,
                    "03": `${PATH}/electricity/electric_discharge_RECTANGLE_04.webm`,
                    "04": `${PATH}/electricity/electric_discharge_RECTANGLE_05.webm`,
                    "05": `${PATH}/electricity/electric_discharge_SQUARE_06.webm`,
                    "06": `${PATH}/electricity/electric_disharge_CIRCLE_01.webm`,
                    "07": `${PATH}/electricity/electric_disharge_CIRCLE_03.webm`,
                    "08": `${PATH}/electricity/electric_dishcarge_CIRCLE_09.webm`,
                    "09": `${PATH}/electricity/electric_dishcarge_SQUARE_08.webm`,
                    "10": `${PATH}/electricity/electric_dishcarge_SQUARE_09.webm`,
                },
                "fire_explosion": {
                    "01": `${PATH}/electricity/electric_fire_explosion_CIRCLE_01.webm`,
                    "02": `${PATH}/electricity/electric_fire_explosion_CIRCLE_02.webm`,
                },
                "shockwave": {
                    "blue": `${PATH}/electricity/electric_shockwave_blue_CIRCLE.webm`,
                    "green": `${PATH}/electricity/electric_shockwave_green_CIRCLE.webm`,
                    "purple": `${PATH}/electricity/electric_shockwave_purple_CIRCLE.webm`,
                    "red": `${PATH}/electricity/electric_shockwave_red_CIRCLE.webm`,
                    "yellow": `${PATH}/electricity/electric_shockwave_yellow_CIRCLE.webm`,
                },
                "wave": `${PATH}/electricity/electric_wave_SQUARE_01.webm`,
                "wheel": `${PATH}/electricity/electric_wheel_loop_RECTANGLE.webm`,
                "wifi": {
                    "01": `${PATH}/electricity/electric_wifi_SQUARE_01.webm`,
                    "02": `${PATH}/electricity/electric_wifi_SQUARE_02.webm`,
                },
                "triangle": `${PATH}/electricity/electrivity_triangle_CONE_01.webm`,
                "ray": {
                    "01": `${PATH}/electricity/lightning_blast_01_r2l.webm`,
                    "02": `${PATH}/electricity/lightning_blast_RAY_02.webm`,
                    "03": `${PATH}/electricity/lightning_blast_RECTANGLE_01.webm`,
                },
                "bolt": {
                    "01": `${PATH}/electricity/lightning_bolt_RECTANGLE_01.webm`,
                    "02": `${PATH}/electricity/lightning_bolt_RECTANGLE_02.webm`,
                    "03": `${PATH}/electricity/lightning_bolt_RECTANGLE_03.webm`,
                    "04": `${PATH}/electricity/lightning_bolt_RECTANGLE_04.webm`,
                    "05": `${PATH}/electricity/lightning_bolt_RECTANGLE_05.webm`,
                    "06": `${PATH}/electricity/lightning_bolt_RECTANGLE_06.webm`,
                    "07": `${PATH}/electricity/lightning_bolt_RECTANGLE_07.webm`,
                },
                "cone": `${PATH}/electricity/lightning_breath_CONE_01.webm`,
                "curves": `${PATH}/electricity/lightning_chaotic_curves_RECTANGLE_01.webm`,
                "ring": `${PATH}/electricity/ring_CIRCLE_01.webm`,
            },
            "energy": {},
            "explosions": {},
            "fire": {},
            "flash": {},
            "level 01": {},
            "level 02": {},
            "magic": {},
            "misc": {},
            "mix": {},
            "simple": {},
            "smoke": {},
            "water": {},
        };
        Sequencer.Database.registerEntries('animated-spell-effects-cartoon', cartoonDatabase);
    }
});